### ISSUE TITLE
test_spdm_responder_csr occur detected memory leaks with the LibFuzzer generated specific mutation seed

### ISSUE THREAD

**Issue by Xiaohanjlll** [DMTF/libspdm#1138]
1.Verified on 320f7c878d004d5757fda9dbc828ab915c7fcbd9
Ubuntu 20.04.4 LTS

cd libspdm
mkdir build_libfuzzer
cd build_libfuzzer
cmake -DARCH=x64 -DTOOLCHAIN=LIBFUZZER -DTARGET=Release -DCRYPTO=mbedtls ..
make copy_sample_key
make
cd bin
./test_spdm_responder_csr ./../../leak-05ddc7d6eff203d93b7cc7932efa73ad62ef98c2

> INFO: Seed: 37083526
INFO: Loaded 1 modules   (11019 inline 8-bit counters): 11019 [0x747db8, 0x74a8c3), 
INFO: Loaded 1 PC tables (11019 PCs): 11019 [0x74a8c8,0x775978), 
./test_spdm_responder_csr: Running 1 inputs 1 time(s) each.
Running: ./../../rsp_csr
set_attribute failed !
set_attribute failed !
set_attribute failed !
set_attribute failed !

=================================================================
==2108506==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 360 byte(s) in 1 object(s) allocated from:
    #0 0x5302ed in malloc (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x5302ed)
    #1 0x597fb1 in allocate_zero_pool /home/test/libspdm_XiaoHan/os_stub/malloclib/malloclib.c:22:14
    #2 0x658385 in my_calloc /home/test/libspdm_XiaoHan/os_stub/cryptlib_mbedtls/sys_call/mem_allocation.c:44:12
    #3 0x5fe494 in eckey_alloc_wrap /home/test/libspdm_XiaoHan/os_stub/mbedtlslib/mbedtls/library/pk_wrap.c:392:17
    #4 0x5fc210 in mbedtls_pk_setup /home/test/libspdm_XiaoHan/os_stub/mbedtlslib/mbedtls/library/pk.c:141:25
    #5 0x596f45 in libspdm_gen_x509_csr /home/test/libspdm_XiaoHan/os_stub/cryptlib_mbedtls/pk/x509.c:1758:15
    #6 0x5aa79f in libspdm_gen_csr /home/test/libspdm_XiaoHan/os_stub/spdm_device_secret_lib_sample/lib.c:335:14
    #7 0x56232c in libspdm_get_response_csr /home/test/libspdm_XiaoHan/library/spdm_responder_lib/libspdm_rsp_csr.c:140:14
    #8 0x5600b5 in libspdm_test_responder_csr_case2 /home/test/libspdm_XiaoHan/unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c:83:5
    #9 0x560314 in libspdm_run_test_harness /home/test/libspdm_XiaoHan/unit_test/fuzzing/test_responder/test_spdm_responder_csr/csr.c:112:5
    #10 0x561414 in LLVMFuzzerTestOneInput /home/test/libspdm_XiaoHan/unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c:124:5
    #11 0x46a781 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x46a781)
    #12 0x455ef2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x455ef2)
    #13 0x45b9a6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x45b9a6)
    #14 0x484662 in main (/home/test/libspdm_XiaoHan/build/bin/test_spdm_responder_csr+0x484662)
    #15 0x7fded6a7d0b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

[test_spdm_responder_csr_leak.zip](https://github.com/DMTF/libspdm/files/9347495/test_spdm_responder_csr_leak.zip)

**Comment by Xiaohanjlll** [comment]
I will check it.
