### ISSUE TITLE
test_spdm_requester_get_measurements occur 32 memory leaks with the initial seed

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#675]
Verified on https://github.com/DMTF/libspdm/commit/91ccef2d3ddf1806dea97993cccfe822448c8a6d
Ubuntu 20.04.2 LTS
```
cd libspdm
mkdir build
cd build
cmake -DARCH=x64 -DTOOLCHAIN=LIBFUZZER -DTARGET=Debug -DCRYPTO=mbedtls ..
make copy_sample_key
make
cd bin
cp -r ~/libspdm/unit_test/fuzzing/seeds ./
./test_spdm_requester_get_measurements ./seeds/test_spdm_requester_get_measurements/get_measurements.raw
INFO: Seed: 368965161
INFO: Loaded 1 modules   (9453 inline 8-bit counters): 9453 [0x6cb530, 0x6cda1d),
INFO: Loaded 1 PC tables (9453 PCs): 9453 [0x6cda20,0x6f28f0),
./test_spdm_requester_get_measurements: Running 1 inputs 1 time(s) each.
Running: ./seeds/test_spdm_requester_get_measurements/get_measurements.raw
ClientNonce - 0a 28 4b 7c 21 b2 d4 3a 54 e7 04 2d 13 d6 62 44 23 71 a5 26 8c e0 24 8e d2 04 3f 94 37 cb 4d 42
spdm_send_spdm_request[0] (0x25):
0000: 11 e0 01 01 0a 28 4b 7c 21 b2 d4 3a 54 e7 04 2d 13 d6 62 44 23 71 a5 26 8c e0 24 8e d2 04 3f 94
0020: 37 cb 4d 42 00
spdm_receive_spdm_response[0] (0x862):
0000: 11 60 00 00 01 87 00 00 05 01 83 00 84 80 00 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05
0020: 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05 05
..
..
..
measurement_record_length - 0x000087
nonce (0x20) - 16 27 0d 2e b6 3c 31 76 c3 74 82 a6 f7 6c 68 83 a8 9e fd 2a b8 e4 4c 14 a2 ea 05 67 4b 89 59 a6

=================================================================
==97960==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 592 byte(s) in 1 object(s) allocated from:
    #0 0x52d26d in malloc (/home/test/libspdm/build/bin/test_spdm_requester_get_measurements+0x52d26d)
    #1 0x574959 in allocate_zero_pool /home/test/libspdm/os_stub/malloclib/malloclib.c:22:14
    #2 0x61d18d in my_calloc /home/test/libspdm/os_stub/cryptlib_mbedtls/sys_call/mem_allocation.c:44:12
    #3 0x5ac93c in ecp_mul_comb /home/test/libspdm/os_stub/mbedtlslib/mbedtls/library/ecp.c:2346:13
    #4 0x5abdfd in mbedtls_ecp_mul_restartable /home/test/libspdm/os_stub/mbedtlslib/mbedtls/library/ecp.c:2704:9
    #5 0x5acf42 in mbedtls_ecp_mul_shortcuts /home/test/libspdm/os_stub/mbedtlslib/mbedtls/library/ecp.c:2815:9
    #6 0x5acd5f in mbedtls_ecp_muladd_restartable /home/test/libspdm/os_stub/mbedtlslib/mbedtls/library/ecp.c:2871:5
    #7 0x5f9540 in ecdsa_verify_restartable /home/test/libspdm/os_stub/mbedtlslib/mbedtls/library/ecdsa.c:669:5
    #8 0x5f9050 in mbedtls_ecdsa_verify /home/test/libspdm/os_stub/mbedtlslib/mbedtls/library/ecdsa.c:718:13
    #9 0x61bb26 in ecdsa_verify /home/test/libspdm/os_stub/cryptlib_mbedtls/pk/ec.c:643:11
    #10 0x576d6e in ecdsa_verify_wrap /home/test/libspdm/library/spdm_crypt_lib/libspdm_crypt_crypt.c:1906:12
    #11 0x577690 in libspdm_asym_verify_hash /home/test/libspdm/library/spdm_crypt_lib/libspdm_crypt_crypt.c:2192:16
    #12 0x56e82f in libspdm_verify_measurement_signature /home/test/libspdm/library/spdm_common_lib/libspdm_com_crypto_service.c:1256:18
    #13 0x561516 in try_spdm_get_measurement /home/test/libspdm/library/spdm_requester_lib/libspdm_req_get_measurements.c:328:18
    #14 0x561f66 in libspdm_get_measurement /home/test/libspdm/library/spdm_requester_lib/libspdm_req_get_measurements.c:518:18
    #15 0x55d145 in test_spdm_requester_get_measurement_case1 /home/test/libspdm/unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c:154:5
    #16 0x55ed34 in run_test_harness /home/test/libspdm/unit_test/fuzzing/test_requester/test_spdm_requester_get_measurements/get_measurements.c:379:5
    #17 0x55fc76 in LLVMFuzzerTestOneInput /home/test/libspdm/unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c:165:5
    #18 0x467701 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/test/libspdm/build/bin/test_spdm_requester_get_measurements+0x467701)
    #19 0x452e72 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/test/libspdm/build/bin/test_spdm_requester_get_measurements+0x452e72)
    #20 0x458926 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/test/libspdm/build/bin/test_spdm_requester_get_measurements+0x458926)
    #21 0x4815e2 in main (/home/test/libspdm/build/bin/test_spdm_requester_get_measurements+0x4815e2)
    #22 0x7f6b412ac0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
..
..
..
SUMMARY: AddressSanitizer: 2080 byte(s) leaked in 32 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

```

**Comment by Xiaohanjlll** [comment]
I will check it.
