### ISSUE TITLE
test_spdm_requester_finish detected memory leak with the initial corpus and aborted the execution

### ISSUE THREAD

**Issue by Zhiqiang520** [DMTF/libspdm#826]
1. Verified on https://github.com/DMTF/libspdm/commit/4beef6e61650fea8a73249f840a4f80c39e36003
Ubuntu 20.04.2 LTS
```
cd libspdm
mkdir build_test_libfuzz
cd build_test_libfuzz
cmake -DARCH=x64 -DTOOLCHAIN=LIBFUZZER -DTARGET=Debug -DCRYPTO=mbedtls ..
make copy_sample_key
make copy_seed
make
cd bin
./test_spdm_requester_finish ./seeds/test_spdm_requester_finish/finish.raw
INFO: Seed: 2658443350
INFO: Loaded 1 modules   (9668 inline 8-bit counters): 9668 [0x6d5530, 0x6d7af4),
INFO: Loaded 1 PC tables (9668 PCs): 9668 [0x6d7af8,0x6fd738),
./test_spdm_requester_finish: Running 1 inputs 1 time(s) each.
Running: ./seeds/test_spdm_requester_finish/finish.raw
th_curr hmac - 37 77 14 1d 7b 9a 38 02 9e c2 80 25 27 ba 60 b5 7b ad ae 57 af 3f 1b ac 1e 88 ef c9 ea c4 38 18
libspdm_send_spdm_request[0] (0x24):
0000: 11 e5 00 00 37 77 14 1d 7b 9a 38 02 9e c2 80 25 27 ba 60 b5 7b ad ae 57 af 3f 1b ac 1e 88 ef c9
0020: ea c4 38 18
libspdm_receive_spdm_response[0] (0x24):
0000: 11 65 00 00 ef 01 00 00 00 00 00 00 00 a0 91 7a d3 40 7f 00 00 00 00 00 00 00 00 00 00 90 c1 77
0020: d3 40 7f 00
verify_data (0x20):
0000: ef 01 00 00 00 00 00 00 00 a0 91 7a d3 40 7f 00 00 00 00 00 00 00 00 00 00 90 c1 77 d3 40 7f 00
th_curr hmac - de c9 0e 2a 5d 00 5b 3a cd 12 83 fe 9e 89 6d e0 89 80 b1 89 7c d2 9f e6 19 0e 13 cb a9 10 c6 64
!!! verify_finish_rsp_hmac - FAIL !!!
th_curr hmac - 37 77 14 1d 7b 9a 38 02 9e c2 80 25 27 ba 60 b5 7b ad ae 57 af 3f 1b ac 1e 88 ef c9 ea c4 38 18
libspdm_send_spdm_request[0] (0x24):
0000: 11 e5 00 00 37 77 14 1d 7b 9a 38 02 9e c2 80 25 27 ba 60 b5 7b ad ae 57 af 3f 1b ac 1e 88 ef c9
0020: ea c4 38 18
libspdm_receive_spdm_response[0] (0x24):
0000: 11 65 00 00 ef 01 00 00 00 00 00 00 00 a0 91 7a d3 40 7f 00 00 00 00 00 00 00 00 00 00 90 c1 77
0020: d3 40 7f 00
verify_data (0x20):
0000: ef 01 00 00 00 00 00 00 00 a0 91 7a d3 40 7f 00 00 00 00 00 00 00 00 00 00 90 c1 77 d3 40 7f 00
th_curr hmac - de c9 0e 2a 5d 00 5b 3a cd 12 83 fe 9e 89 6d e0 89 80 b1 89 7c d2 9f e6 19 0e 13 cb a9 10 c6 64
!!! verify_finish_rsp_hmac - FAIL !!!

=================================================================
==279552==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 108 byte(s) in 1 object(s) allocated from:
    #0 0x52f26d in malloc (/home/test/libspdm/build_test_libfuzz/bin/test_spdm_requester_finish+0x52f26d)
    #1 0x57a199 in allocate_zero_pool /home/test/libspdm/os_stub/malloclib/malloclib.c:22:14
    #2 0x61e015 in libspdm_sha256_new /home/test/libspdm/os_stub/cryptlib_mbedtls/hash/sha.c:26:19
    #3 0x57aa0d in libspdm_hash_new /home/test/libspdm/library/spdm_crypt_lib/libspdm_crypt_crypt.c:613:12
    #4 0x5692c1 in libspdm_append_message_k /home/test/libspdm/library/spdm_common_lib/libspdm_com_context_data.c:1536:71
    #5 0x56a413 in libspdm_append_message_f /home/test/libspdm/library/spdm_common_lib/libspdm_com_context_data.c:1766:26
    #6 0x56152b in libspdm_try_send_receive_finish /home/test/libspdm/library/spdm_requester_lib/libspdm_req_finish.c:140:14
    #7 0x56200d in libspdm_send_receive_finish /home/test/libspdm/library/spdm_requester_lib/libspdm_req_finish.c:319:18
    #8 0x55f1bd in libspdm_test_send_receive_finish_case1 /home/test/libspdm/unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c:149:14
    #9 0x55f654 in libspdm_run_test_harness /home/test/libspdm/unit_test/fuzzing/test_requester/test_spdm_requester_finish/finish.c:182:5
    #10 0x560504 in LLVMFuzzerTestOneInput /home/test/libspdm/unit_test/fuzzing/spdm_unit_fuzzing_common/toolchain_harness.c:124:5
    #11 0x469701 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/test/libspdm/build_test_libfuzz/bin/test_spdm_requester_finish+0x469701)
    #12 0x454e72 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/test/libspdm/build_test_libfuzz/bin/test_spdm_requester_finish+0x454e72)
    #13 0x45a926 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/test/libspdm/build_test_libfuzz/bin/test_spdm_requester_finish+0x45a926)
    #14 0x4835e2 in main (/home/test/libspdm/build_test_libfuzz/bin/test_spdm_requester_finish+0x4835e2)
    #15 0x7f40d35e40b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
...
...
...
SUMMARY: AddressSanitizer: 1384 byte(s) leaked in 14 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```
2. the same issue occur when run `./test_spdm_responder_finish_rsp ./seeds/test_spdm_responder_finish_rsp/finish.raw`.

**Comment by Xiaohanjlll** [comment]
I will check it.
