### ISSUE TITLE
test_spdm_responder_measurements occur one memory leaks with the LibFuzzer generated specific mutation seed

### ISSUE THREAD

**Issue by yaohuixguo** [DMTF/libspdm#961]
Verified on d0815da9b12e7112fc144167c9397b24da91eb17
Ubuntu 20.04.4 LTS

    cd libspdm
    mkdir build_libfuzzer
    cd build_libfuzzer
    cmake -DARCH=x64 -DTOOLCHAIN=LIBFUZZER -DTARGET=Release -DCRYPTO=mbedtls ..
    make copy_sample_key
    make
    cd bin
    ./test_spdm_responder_measurements ./test_spdm_responder_measurements_leak
    INFO: Seed: 3100107272
    INFO: Loaded 1 modules   (11064 inline 8-bit counters): 11064 [0x7364c9, 0x739001),
    INFO: Loaded 1 PC tables (11064 PCs): 11064 [0x739008,0x764388),
    ./test_spdm_responder_measurements: Running 1 inputs 1 time(s) each.
    Running: ./test_spdm_responder_measurements_leak

    =================================================================
    ==3866913==ERROR: LeakSanitizer: detected memory leaks

    Direct leak of 108 byte(s) in 1 object(s) allocated from:
        #0 0x5302ed in malloc (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x5302ed)
        #1 0x596941 in allocate_zero_pool (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x596941)
        #2 0x65059d in libspdm_sha256_new (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x65059d)
        #3 0x5976d5 in libspdm_hash_new (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x5976d5)
        #4 0x580ea5 in libspdm_append_message_m (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x580ea5)
        #5 0x564415 in libspdm_get_response_measurements (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x564415)
        #6 0x55fcdc in libspdm_test_responder_measurements_case1 (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x55fcdc)
        #7 0x56141c in libspdm_run_test_harness (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x56141c)
        #8 0x562564 in LLVMFuzzerTestOneInput (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x562564)
        #9 0x46a781 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x46a781)
        #10 0x455ef2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x455ef2)
        #11 0x45b9a6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x45b9a6)
        #12 0x484662 in main (/home/gyh/libspdm/build_libfuzzer/bin/test_spdm_responder_measurements+0x484662)
        #13 0x7f3e10b310b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16

    SUMMARY: AddressSanitizer: 108 byte(s) leaked in 1 allocation(s).

    INFO: a leak has been found in the initial corpus.

    INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
[test_spdm_responder_measurements_leak.zip](https://github.com/DMTF/libspdm/files/8937080/test_spdm_responder_measurements_leak.zip)

**Comment by yaohuixguo** [comment]
I will check it
